### ISSUE TITLE
Not working on RPi2

### ISSUE THREAD

**Issue by bhaskarndas** [tommistolercz/plugin.video.vk#102]
It doesn't open at all in RPi2.

**Comment by tommistolercz** [comment]
Please try these simple steps:
- update addon to the newest version (v1.8.0) 
- go to addon settings > USER tab > click LOGOUT USER button
- close settings with OK(!), restart Kodi
- run the addon and re-login with your VK credentials

**Comment by bhaskarndas** [comment]
New version also not working on RPi2 I have Kodi Leia
