### ISSUE TITLE
Authorization issue in new version

### ISSUE THREAD

**Issue by bhaskarndas** [tommistolercz/plugin.video.vk#105]
When I give userid and password it gives 'authorization error'

Platform : Kodi Leia for RPI2

Version of plugin- 1.8.0

**Comment by ivoruetsche** [comment]
Same here:
2021-08-12 21:17:35.263 T:1401905920   ERROR: plugin.video.vk: VK auth error!

**Comment by tommistolercz** [comment]
Solved in v2.0.0

**Comment by midenok** [comment]
No, it still doesn't work
