### ISSUE TITLE
Does a private VK.com profile work properly with this plugin?

### ISSUE THREAD

**Issue by SingleMalt2104** [tommistolercz/plugin.video.vk#70]
Hello Mr Mistoler,

I am asking myself if my "VK error" problem could be the result of a permission rights problem with my privacy account settings on the VK.com site. As indicated in the subject line I have configured my account as a "private profile account". Could this be the case? What privacy settings could lead to (access-)problems with your plugin?

After deleting the old "vkuseraccesstoken" entry in the settings.xml file I could successfully re-enter my credentials by executing the plugin. Therefore I think my access related problems could be due to missing permission rights for the plugin within my VK.com account, even though the properties of the plugin state to have all needed rights.

Also every time I access my VK.com account with KODI and your plugin, VK.com sends me an email stating that an unknown access onto my account has taken place and I should consider actions if it was not my doing. So maybe the plugin has not yet properly authorized on my end to work the way it should?

Best regards, SingleMalt2104

**Comment by tommistolercz** [comment]
Hello again,

just fyi I've done a quick test and it looks like the addon works fine with mentioned setting: `Profile type=Private` (VK.com > Settings > Privacy).

The cause of your issues is (imho) unicode-related, as explained in #66.

**Comment by SingleMalt2104** [comment]
Thanks for testing your addon with VK.com's "private" profile settings. I am looking forward to test your next update v1.2.0, and that it hopefully fixes my VK.com access problems.
